#!/bin/sh 
set -e

source `dirname $0`/../configs.sh

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t graphicsmagick_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

gm_local_path=$tempdir/graphcismagick-${GRAPHICS_MAGICK_VERSION}.tgz

libpng_local_path=$tempdir/libpng-${LIBPNG_VERSION}.tgz

echo ">>> Downloading libpng sources"

libpng_sources=$tempdir/libpng-${LIBPNG_VERSION}.tar.gz
curl ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng15/libpng-${LIBPNG_VERSION}.tar.gz > $libpng_sources

tar -C $tempdir -x -z -f $libpng_sources

echo ">>> Building libpng"

# build and package libpng for heroku
vulcan build -v \
  -s $tempdir/libpng-${LIBPNG_VERSION} \
  -n libpng\
  -o $libpng_local_path

echo ">>> Uploading libpng artifact"
echo "    to ${S3_BUCKET}/${LIBPNG_REMOTE_PATH}"
echo "    from ${libpng_local_path}"

$basedir/aws/s3 put $S3_BUCKET $LIBPNG_REMOTE_PATH $libpng_local_path

echo ">>> Downloading graphicsmagick"

gm_sources=$tempdir/graphicsmagick-${LIBPNG_VERSION}.tar.gz
#curl ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/1.3/GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.gz > $gm_sources
curl http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.gz > $gm_sources

tar -C $tempdir -x -z -f $gm_sources

echo ">>> Building graphicsmagick"

# build and package imagemagick for heroku
vulcan build -v \
  -s $tempdir/GraphicsMagick-$GRAPHICS_MAGICK_VERSION \
  -n graphicsmagick \
  -o $gm_local_path \
  --deps $LIBPNG_REMOTE_PATH

echo ">>> Uploading graphics magick artifact"
echo "    to ${S3_BUCKET}/${REMOTE_PATH}"
echo "    from ${gm_local_path}"

$basedir/aws/s3 put $S3_BUCKET $REMOTE_PATH $gm_local_path
