#! /bin/bash 
set -e

source `dirname $0`/../configs.sh

pushd `dirname $0`/.. >> /dev/null
home=`pwd`
popd >> /dev/null

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t graphicsmagick_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo ">>> Building zlib"

zlib_local_path=$tempdir/zlib-${ZLIB_VERSION}.tgz

# build and package zlib for heroku
vulcan build -v \
  -s $home/vendor/zlib-${ZLIB_VERSION} \
  -n zlib\
  -o $zlib_local_path

echo ">>> Uploading zlib"

$basedir/aws/s3 put $S3_BUCKET $ZLIB_REMOTE_PATH $zlib_local_path

echo ">>> Building libpng"

libpng_local_path=$tempdir/libpng-${LIBPNG_VERSION}.tgz

# build and package libpng for heroku
vulcan build -v \
  -s $home/vendor/libpng-${LIBPNG_VERSION} \
  -n libpng\
  -o $libpng_local_path \
  --deps http://s3.amazonaws.com/$S3_BUCKET/$ZLIB_REMOTE_PATH

echo ">>> Uploading libpng artifact"
echo "    to ${S3_BUCKET}/${LIBPNG_REMOTE_PATH}"
echo "    from ${libpng_local_path}"

$basedir/aws/s3 put $S3_BUCKET $LIBPNG_REMOTE_PATH $libpng_local_path

echo ">>> Building nasm"

nasm_local_path=$tempdir/nasm-${NASM_VERSION}.tgz
# build and package nasm for heroku
vulcan build -v \
  -s $home/vendor/nasm-${NASM_VERSION} \
  -n nasm\
  -o $nasm_local_path

echo ">>> Uploading nasm artifact"
echo "    to ${S3_BUCKET}/${NASM_REMOTE_PATH}"
echo "    from ${nasm_local_path}"

$basedir/aws/s3 put $S3_BUCKET $NASM_REMOTE_PATH $nasm_local_path

echo ">>> Building libjpeg-turbo"

libjpeg_turbo_local_path=$tempdir/libjpeg_turbo-${LIBJPEG_TURBO_VERSION}.tgz
# build and package libpng for heroku
vulcan build -v \
  -s $home/vendor/libjpeg-turbo-${LIBJPEG_TURBO_VERSION} \
  -n libjpeg_turbo\
  -o $libjpeg_turbo_local_path \
  --deps http://s3.amazonaws.com/$S3_BUCKET/$ZLIB_REMOTE_PATH \
  http://s3.amazonaws.com/$S3_BUCKET/$NASM_REMOTE_PATH \

echo ">>> Uploading libjpeg-turbo artifact"
echo "    to ${S3_BUCKET}/${LIBJPEG_TURBO_REMOTE_PATH}"
echo "    from ${libjpeg_turbo_local_path}"

$basedir/aws/s3 put $S3_BUCKET $LIBJPEG_TURBO_REMOTE_PATH $libjpeg_turbo_local_path

echo ">>> Downloading graphicsmagick"

gm_local_path=$tempdir/graphcismagick-${GRAPHICS_MAGICK_VERSION}.tgz
gm_sources=$tempdir/graphicsmagick-${LIBPNG_VERSION}.tar.gz
#curl ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/1.3/GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.gz > $gm_sources
curl http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-${GRAPHICS_MAGICK_VERSION}.tar.gz > $gm_sources

tar -C $tempdir -x -z -f $gm_sources

echo ">>> Building graphicsmagick"

# build and package imagemagick for heroku
vulcan build -v \
  -s $tempdir/GraphicsMagick-$GRAPHICS_MAGICK_VERSION \
  -n graphicsmagick \
  -o $gm_local_path \
  --deps http://s3.amazonaws.com/$S3_BUCKET/$LIBPNG_REMOTE_PATH \
  http://s3.amazonaws.com/$S3_BUCKET/$ZLIB_REMOTE_PATH \
  http://s3.amazonaws.com/$S3_BUCKET/$NASM_REMOTE_PATH \
  http://s3.amazonaws.com/$S3_BUCKET/$LIBJPEG_TURBO_REMOTE_PATH

echo ">>> Uploading graphics magick artifact"
echo "    to ${S3_BUCKET}/${REMOTE_PATH}"
echo "    from ${gm_local_path}"

$basedir/aws/s3 put $S3_BUCKET $REMOTE_PATH $gm_local_path
